### ISSUE TITLE
Spiel beendet sich noch nicht richtig

### ISSUE THREAD

**Issue by JayJayJay1** [JavaJumperStudios/Saboteur#63]
- Mindestanzahl Spieler hinzufügen
- zu properties-Datei hinzufügen
- sicherstellen, dass Sieg und Verlustbedingungen funktionieren

**Comment by Schlappi** [comment]
Was genau funktioniert denn nicht? Bin nich sicher was hier gemacht werden muss

**Comment by JayJayJay1** [comment]
Anscheinend ist das schon gefixt worden
