### ISSUE TITLE
Kollisionen mit übertragen

### ISSUE THREAD

**Issue by JayJayJay1** [JavaJumperStudios/Saboteur#65]
- Kollisionen beim Karte übertragen mit übertragen
- Hashwerte abgleichen
- auf linux wird jedes mal eine neue datei "room.map          " gespeichert (fixen)

**Comment by Schlappi** [comment]
Da die Kollision serverseitig berechnet wird, ist es überhaupt sinnvoll diese mit zu übertragen?
