### ISSUE TITLE
Spielerverwaltung verbessern

### ISSUE THREAD

**Issue by JayJayJay1** [JavaJumperStudios/Saboteur#80]
- das Spiel ist verbuggt sobald sich Spieler ausloggen (fixen)
- Packet03 ist im ServerListener auskommentiert (?)
- einloggen und ausloggen loggen
- bei ausloggen winconditions prüfen

**Comment by Schlappi** [comment]
Ich glaub das mit dem auskommentierten Code kann weg das war noch alt :D

**Comment by JayJayJay1** [comment]
Okay :+1:
